services:
  - type: web
    name: ai-doctor-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python gradio_app.py"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
